# Generated by Django 4.1.7 on 2023-05-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
